=== Quartenion/GRD/ACTIVIDADES/dlib.dtd
<!ELEMENT article (meta, abstract?, keywords?, body, references?)>

<!-- Metadata -->
<!ELEMENT meta (title, date?, volume?, number?, authors, journal?, version?)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT volume (#PCDATA)>
<!ELEMENT number (#PCDATA)>
<!ELEMENT journal (#PCDATA)>
<!ELEMENT version (#PCDATA)>

<!-- Authors -->
<!ELEMENT authors (author+)>
<!ELEMENT author (name, affiliation*, email?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT affiliation (institute?, university?, country?)>
<!ELEMENT institute (#PCDATA)>
<!ELEMENT university (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT email (#PCDATA)>

<!-- Abstract -->
<!ELEMENT abstract (#PCDATA)>

<!-- Keywords -->
<!ELEMENT keywords (keyword+)>
<!ELEMENT keyword (#PCDATA)>

<!-- Body -->
<!ELEMENT body (section+)>
<!ELEMENT section (sect_title?, (paragraph | figure | table | list | subsection)*)>
<!ELEMENT sect_title (#PCDATA)>
<!ELEMENT subsection (sect_title?, (paragraph | figure | table | list | subsection)*)>

<!-- Paragraph -->
<!ELEMENT paragraph (#PCDATA | ref | link)*>
<!ELEMENT ref (#PCDATA)> 
<!ELEMENT link (#PCDATA)>

<!-- Figure -->
<!ELEMENT figure (caption?, graphic?)>
<!ELEMENT caption (#PCDATA)>
<!ELEMENT graphic (#PCDATA)>

<!-- Table -->
<!ELEMENT table (caption?, tgroup?)>
<!ELEMENT tgroup (#PCDATA)>

<!-- Lists -->
<!ELEMENT list (item+)>
<!ELEMENT item (#PCDATA)>

<!-- References -->
<!ELEMENT references (reference+)>
<!ELEMENT reference (rtitle, rauthors?, rsource?, ryear?, rurl?)>
<!ELEMENT rtitle (#PCDATA)>
<!ELEMENT rauthors (rauthor+)>
<!ELEMENT rauthor (#PCDATA)>
<!ELEMENT rsource (#PCDATA)>
<!ELEMENT ryear (#PCDATA)>
<!ELEMENT rurl (#PCDATA)>

=== Quartenion/GRD/ACTIVIDADES/dlib.xml
<?xml version="1.0"?>
<!DOCTYPE article SYSTEM "dlib.dtd">
<article>
    <meta>
        <title>Extraction of References Using Layout and Formatting Information from Scientific Articles</title>
        <date>September/October 2013</date>
        <volume>19</volume>
        <number>9/10</number>
        <authors>
            <author>
                <name>Roman Kern</name>
                <affiliation>
                <institute>Knowledge Technologies Institute</institute>
                <university>Graz University of Technology</university>
                <country>Austria</country>
                </affiliation>
                <email>rkern@tugraz.at</email>
            </author>
            <author>
                <name>Stefan Klampfl</name>
                <affiliation>
                <institute>Know-Center</institute>
                <country>Austria</country>
                </affiliation>
                <email>sklampfl@know-center.at</email>
            </author>
        </authors>
        <journal>D-Lib Magazine</journal>
        <version>doi:10.1045/september2013-kern</version>
    </meta>
  
    <abstract>
        The automatic extraction of reference meta-data is an important requirement for the efficient management of collections of scientific literature. 
        An existing powerful state-of-the-art system for extracting references from a scientific article is ParsCit; however, it requires the input document 
        to be converted into plain text, thereby ignoring most of the formatting and layout information. In this paper, we quantify the contribution of this 
        additional information to the reference extraction performance by an improved preprocessing using the information contained in PDF files and retraining 
        sequence classifiers on an enhanced feature set. We found that the detection of columns, reading order, and decorations, as well as the inclusion of 
        layout information improves the retrieval of reference strings, and the classification of reference token types can be improved using additional font 
        information. These results emphasize the importance of layout and formatting information for the extraction of meta-data from scientific articles.
    </abstract>

    <keywords>
        <keyword>Content Analysis and Indexing</keyword>
        <keyword>Meta-data Extraction</keyword>
        <keyword>Natural Language Processing</keyword>
        <keyword>Text Analysis</keyword>
        <keyword>Supervised Machine Learning</keyword>
    </keywords>

    <body>
        <section>
            <sect_title>1. Introduction</sect_title>
            <paragraph>
                Scientific articles usually conclude with a section that acknowledges relevant and related work in the form of a list of citations or references. 
                Researchers often use this information to search for literature that is relevant for their own work or for a specific field of research. 
                With the growth of the global volume of scientific literature reaching unprecedented levels, there is an increasing demand for automated processing 
                systems that support researchers in this task, e.g., through the creation of citation networks such as CiteSeer<ref>[5]</ref>, which allow a convenient 
                navigation through a specific field of research forward and backward in time.
            </paragraph>
            <paragraph>
                The automated extraction of reference meta-data requires the detection of the reference section within a paper, the segmentation of individual reference 
                strings, and the labelling of single tokens within each string as to which field they belong (e.g., author, title, year, journal). These are challenging 
                tasks given the variety of different journal layouts and formatting of reference strings. Several approaches have been proposed using unsupervised methods 
                <ref>[3]</ref> and template matching <ref>[7]</ref>; however, the most promising method has been the supervised classification of sequences, e.g., through 
                Hidden Markov Models (HMMs) <ref>[14]</ref> or Conditional Random Fields (CRFs) <ref>[12]</ref>. The sequence classification approach has also been 
                prominently used for the extraction of other types of meta-data from scientific articles <ref>[11, 6, 8]</ref>. ParsCit <ref>[4]</ref> is an existing 
                state-of-the-art reference extraction system that uses heuristics to detect and segment references within a scientific article, and CRFs to assign labels to 
                the tokens within each reference string. However, this system assumes the input article was provided in raw text format, thereby ignoring most of the formatting 
                and layout information, such as columns, line indentation, or font style. As these features certainly help humans to read and understand references, their 
                inclusion should intuitively improve the performance of the reference extraction.
            </paragraph>
            <paragraph>
                In this paper we quantify the contribution of formatting and layout information provided by PDF files, the most common format of scientific literature today,
                to the reference extraction performance. In particular, we incorporate information about columns, line gaps and indentations, and font styles into both the 
                extraction of reference strings and the classification of their tokens. We retrained ParsCit on a representative document set using both the original feature
                set in <ref>[4]</ref> and a layout-enhanced feature set. We also compare the performance values obtained by different sequence classifiers and by the out-of-the-box 
                <link>ParsCit</link> system available for download.
            </paragraph>
            <paragraph>
                This paper is structured as follows. In section 2 we devise the individual steps of our reference extraction algorithm and highlight the enhancements we made with respect 
                to the original ParsCit system. In section 3 we separately evaluate the individual stages of our algorithm, reference segmentation and token classification. We discuss the 
                results in section 4 before we conclude with an outlook to future work in section 5.
            </paragraph>
        </section>

        <section>
            <sect_title>2. Algorithm</sect_title>
            <paragraph>
                In this section we describe the individual steps of our reference extraction algorithm. It takes a scientific article in PDF format as input and produces a list of
                references with categorized tokens.
            </paragraph>
            <subsection>
                <sect_title>2.1 Reference Line Extraction</sect_title>
                <paragraph>
                    The first step is to find the lines containing the references within an article. The starting point for the reference line extraction is a set of contiguous text 
                    blocks of the input PDF file. These text blocks are provided by an <link>open source tool</link> that builds upon the output of the <link>PDFBox</link> library. 
                    The resulting physical structure consists of a list of text blocks hierarchically organized into lines, words, and characters, as well as the reading order of blocks 
                    within the document <ref>[1]</ref>. Most importantly, this block structure effectively provides a segmentation of the text into single columns, a fact that is particularly 
                    helpful for reference extraction.
                </paragraph>
                <paragraph>
                    The procedure for extracting the reference lines is similar to the preprocessing step of the original ParsCit algorithm <ref>[4]</ref>. We iterate over all blocks in the reading 
                    order and use a regular expression to find the reference headers, which we assume to be one of "References", "Bibliography", "References and Notes", "Literature cited", 
                    and common variations of those strings (e.g., uppercase variants). Additionally we allow five extra characters in the heading, in case there is a section numbering or a 
                    related decoration. Then we collect all lines until we encounter either another section heading, starting with "Acknowledgement", "Autobiographical", "Table", "Appendix", 
                    "Exhibit", "Annex", "Fig", or "Notes", or the end of the document.
                </paragraph>
                <paragraph>
                    Compared with the original ParsCit system, we incorporated additional layout information into the reference line extraction in three ways. First, column information is implicitly 
                    provided through the consideration of text blocks. Second, we ignored the content of decoration blocks (headers and footers consisting of page numbers, authors, or journal names), 
                    which we computed by associating blocks across neighboring pages based on their content and geometrical position <ref>[10]</ref>. Finally, we ignored all lines following a vertical gap that 
                    is larger than the average gap size plus two times the standard deviation of gap sizes. This criterion has been introduced as the block of references is often followed by footnotes, 
                    copyright information or other types of text which is visually separated from the references by a bigger gap.
                </paragraph>
                <paragraph>
                    The output of the references line extraction step is a collection of lines containing the article's references.
                </paragraph>
            </subsection>
            <subsection>
